### ISSUE TITLE
Missing Option Additional Servers

### ISSUE THREAD

**Issue by smaegley** [fl4p/influxdb-udp-relay#1]
I believe I have installed this add on correctly, however when I attempt to start it I get the following error.

`Missing option 'additional_servers' in root in influxdb-udp-relay (2af0a32d_influxdb-udp-relay). `

I see that additional_servers can be added in the Optional Configuration Options on the config, but I have no idea what an additional server should be or how to format it.  Any ideas?

**Comment by fl4p** [comment]
Hi, that's a bug, i'll upload a fix soon

**Comment by fl4p** [comment]
i just pushed an update. does it work for you now?

**Comment by smaegley** [comment]
It now starts but I haven't been able to get my proxmox metrics server to connect yet.  I'm sure I've got that configuration screwed up over there so I'll keep plugging away at it.

I do see this in the log.  Not sure if those services starting and stopping is a new issue or not.

```
s6s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
Traceback (most recent call last):
  File "/app/main.py", line 115, in <module>
    main()
  File "/app/main.py", line 101, in main
    config = ha.read_hass_configuration_yaml()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/ha.py", line 20, in read_hass_configuration_yaml
    return yaml.safe_load(fp)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yaml/__init__.py", line 125, in safe_load
    return load(stream, SafeLoader)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yaml/__init__.py", line 81, in load
    return loader.get_single_data()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yaml/constructor.py", line -rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
Traceback (most recent call last):
  File "/app/main.py", line 115, in <module>
    main()
  File "/app/main.py", line 101, in main
    config = ha.read_hass_configuration_yaml()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/ha.py", line 20, in read_hass_configuration_yaml
    return yaml.safe_load(fp)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yaml/__init__.py", line 125, in safe_load
    return load(stream, SafeLoader)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yaml/__init__.py", line 81, in load
    return loader.get_single_data()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yaml/constructor.py", line 51, in get_single_data
    return self.construct_document(node)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yaml/constructor.py", line 60, in construct_document
    for dummy in generator:
  File "/usr/lib/python3.11/site-packages/yaml/constructor.py", line 413, in construct_yaml_map
    value = self.construct_mapping(node)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yaml/constructor.py", line 218, in construct_mapping
    return super().construct_mapping(node, deep=deep)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yaml/constructor.py", line 143, in construct_mapping
    value = self.construct_object(value_node, deep=deep)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yaml/constructor.py", line 100, in construct_object
    data = constructor(self, node)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yaml/constructor.py", line 427, in construct_undefined
    raise ConstructorError(None, None,
yaml.constructor.ConstructorError: could not determine a constructor for the tag '!include_dir_merge_named'
  in "/config/configuration.yaml", line 15, column 11
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
```

**Comment by fl4p** [comment]
pushed another update, please try again

**Comment by smaegley** [comment]
Looks like the same messages with different line numbers. Let me know if there is anything else you need me to look at. Happy to try to help.

```
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
Traceback (most recent call last):
  File "/app/main.py", line 118, in <module>
    main()
  File "/app/main.py", line 104, in main
    config = ha.read_hass_configuration_yaml()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/ha.py", line 31, in read_hass_configuration_yaml
    return yaml.safe_load(fp)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yaml/__init__.py", line 125, in safe_load
    return load(stream, SafeLoader)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yaml/__init__.py", line 81, in load
    return loader.get_single_data()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yaml/constructor.py", line 51, in get_single_data
    return self.construct_document(node)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yaml/constructor.py", line 60, in construct_document
    for dummy in generator:
  File "/usr/lib/python3.11/site-packages/yaml/constructor.py", line 413, in construct_yaml_map
    value = self.construct_mapping(node)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yaml/constructor.py", line 218, in construct_mapping
    return super().construct_mapping(node, deep=deep)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yaml/constructor.py", line 143, in construct_mapping
    value = self.construct_object(value_node, deep=deep)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yaml/constructor.py", line 100, in construct_object
    data = constructor(self, node)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yaml/constructor.py", line 427, in construct_undefined
    raise ConstructorError(None, None,
yaml.constructor.ConstructorError: could not determine a constructor for the tag '!secret'
  in "/config/configuration.yaml", line 18, column 10
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
```

**Comment by fl4p** [comment]
look for custom tag yaml tags in your home assistant condiguration.yaml and post them here. custom tags start with `!`

**Comment by smaegley** [comment]
I have a bunch. Not sure if you want the whole tag or just the type so I gave you the whole thing.

- !include groups.yaml
- !include automations.yaml
- !include scripts.yaml
- !include scenes.yaml
- !include_dir_merge_named themes
- !secret spotcast_sp_dc
- !secret spotcast_sp_key
- !secret proxmoxve_username
- !secret proxmoxve_password
- !secret influxdb_password
- !secret alarm_control_panel_code
- !secret waqi_token
- !secret ffmpeg_input
- !secret sleepiq_username
- !secret sleepiq_password

**Comment by fl4p** [comment]
i've pushed another update wich implements all tags

**Comment by smaegley** [comment]
Looks like it now can't connect to the influxDB.  I looked at the host and it looks correct.

... s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
14:43:24 INFO [main] Connecting InfluxDB homeassistant@a0d7b954_influxdb (port=8086 ssl=False)
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/urllib3/connection.py", line 203, in _new_conn
    sock = connection.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/urllib3/util/connection.py", line 60, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/socket.py", line 962, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno -5] Name has no usable address
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/urllib3/connectionpool.py", line 790, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/urllib3/connectionpool.py", line 496, in _make_request
    conn.request(
  File "/usr/lib/python3.11/site-packages/urllib3/connection.py", line 395, in request
    self.endheaders()
  File "/usr/lib/python3.11/http/client.py", line 1281, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.11/http/client.py", line 1041, in _send_output
    self.send(msg)
  File "/usr/lib/python3.11/http/client.py", line 979, in send
    self.connect()
  File "/usr/lib/python3.11/site-packages/urllib3/connection.py", line 243, in connect
    self.sock = self._new_conn()
                ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/urllib3/connection.py", line 210, in _new_conn
    raise NameResolutionError(self.host, self, e) from e
urllib3.exceptions.NameResolutionError: <urllib3.connection.HTTPConnection object at 0x7fde3bef47d0>: Failed to resolve 'a0d7b954_influxdb' ([Errno -5] Name has no usable address)
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/urllib3/connectionpool.py", line 844, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/urllib3/util/retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='a0d7b954_influxdb', port=8086): Max retries exceeded with url: /query?q=SHOW+MEASUREMENTS&db=homeassistant (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7fde3bef47d0>: Failed to resolve 'a0d7b954_influxdb' ([Errno -5] Name has no usable address)"))
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/app/main.py", line 117, in <module>
    main()
  File "/app/main.py", line 109, in main
    writers.append(InfluxDBWriter(influxdb_conf))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/main.py", line 58, in __init__
    logger.info('Measurements: %s', ','.join(map(lambda m: m.get('name', m), self.client.get_list_measurements())))
                                                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/influxdb/client.py", line 653, in get_list_measurements
    return list(self.query("SHOW MEASUREMENTS").get_points())
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/influxdb/client.py", line 445, in query
    response = self.request(
               ^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/influxdb/client.py", line 274, in request
    response = self._session.request(
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='a0d7b954_influxdb', port=8086): Max retries exceeded with url: /query?q=SHOW+MEASUREMENTS&db=homeassistant (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7fde3bef47d0>: Failed to resolve 'a0d7b954_influxdb' ([Errno -5] Name has no usable address)"))
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped ...

![image](https://github.com/fl4p/influxdb-udp-relay/assets/37872989/13ffa593-32ce-4b30-bacb-2d5be8c12fe4)

**Comment by fl4p** [comment]
Rather than `a0d7b954_influxdb` use `a0d7b954-influxdb`

**Comment by smaegley** [comment]
Sorry - my mistake on that one.  Here is the latest.


```
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
20:09:42 INFO [main] Connecting InfluxDB homeassistant@a0d7b954-influxdb (port=8086 ssl=False)
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/urllib3/connection.py", line 203, in _new_conn
    sock = connection.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/urllib3/util/connection.py", line 85, in create_connection
    raise err
  File "/usr/lib/python3.11/site-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
OSError: [Errno 113] Host is unreachable
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/urllib3/connectionpool.py", line 790, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/urllib3/connectionpool.py", line 496, in _make_request
    conn.request(
  File "/usr/lib/python3.11/site-packages/urllib3/connection.py", line 395, in request
    self.endheaders()
  File "/usr/lib/python3.11/http/client.py", line 1281, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.11/http/client.py", line 1041, in _send_output
    self.send(msg)
  File "/usr/lib/python3.11/http/client.py", line 979, in send
    self.connect()
  File "/usr/lib/python3.11/site-packages/urllib3/connection.py", line 243, in connect
    self.sock = self._new_conn()
                ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/urllib3/connection.py", line 218, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f3461b20710>: Failed to establish a new connection: [Errno 113] Host is unreachable
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/urllib3/connectionpool.py", line 844, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/urllib3/util/retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /query?q=SHOW+MEASUREMENTS&db=homeassistant (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3461b20710>: Failed to establish a new connection: [Errno 113] Host is unreachable'))
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/app/main.py", line 117, in <module>
    main()
  File "/app/main.py", line 109, in main
    writers.append(InfluxDBWriter(influxdb_conf))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/main.py", line 58, in __init__
    logger.info('Measurements: %s', ','.join(map(lambda m: m.get('name', m), self.client.get_list_measurements())))
                                                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/influxdb/client.py", line 653, in get_list_measurements
    return list(self.query("SHOW MEASUREMENTS").get_points())
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/influxdb/client.py", line 445, in query
    response = self.request(
               ^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/influxdb/client.py", line 274, in request
    response = self._session.request(
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /query?q=SHOW+MEASUREMENTS&db=homeassistant (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3461b20710>: Failed to establish a new connection: [Errno 113] Host is unreachable'))
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
```


My InfluxDB options do require auth and SSL


```
auth: true
reporting: true
ssl: true
certfile: fullchain.pem
keyfile: privkey.pem
envvars: []
leave_front_door_open: false
```

**Comment by fl4p** [comment]
does it work if you put the LAN ip address as host ?

**Comment by smaegley** [comment]
Nope. I even tried turning off SSL on the InfluxDB to see if thad had an effect, and it didn't.

```
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
20:26:43 INFO [main] Connecting InfluxDB homeassistant@10.0.1.126 (port=8086 ssl=False)
Traceback (most recent call last):
  File "/app/main.py", line 117, in <module>
    main()
  File "/app/main.py", line 109, in main
    writers.append(InfluxDBWriter(influxdb_conf))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/main.py", line 58, in __init__
    logger.info('Measurements: %s', ','.join(map(lambda m: m.get('name', m), self.client.get_list_measurements())))
                                                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/influxdb/client.py", line 653, in get_list_measurements
    return list(self.query("SHOW MEASUREMENTS").get_points())
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/influxdb/client.py", line 445, in query
    response = self.request(
               ^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/influxdb/client.py", line 302, in request
    raise InfluxDBClientError(response.content, response.status_code)
influxdb.exceptions.InfluxDBClientError: 401: {"error":"authorization failed"}
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
```

**Comment by fl4p** [comment]
seems to work. now you need to fix authorization with username and password

**Comment by smaegley** [comment]
I was able to get it to run by changing my config from using !secret for the password to putting the password directly in the config.

**Comment by smaegley** [comment]
Fabian - Any idea why I would get this error now?  it seems like it is trying DB='open_pe'

`19:17:51 ERROR [main] Error writing batch: 404: {"error":"database not found: \"open_pe\""}`

**Comment by fl4p** [comment]
Just pushed another update, try again

**Comment by smaegley** [comment]
It is now working.
